In [1]:
import spacy
nlp =spacy.load("en_core_web_sm")

In [2]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [3]:
doc= nlp('Tesla accuired twitter for $45 billion ')
for ent in doc.ents:
  print(ent.text , "|",ent.label_)

$45 billion | MONEY

In [4]:
from spacy.tokens import Span
s1 = Span( doc,0,1,label="ORG")
s2 = Span(doc ,2,3,label="ORG")


doc.set_ents([s1,s2],default="unmodified")

Bag of words below:

In [5]:
import pandas as pd
import numpy as np

In [7]:
df= pd.read_csv('spam.csv')
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [10]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [11]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test= train_test_split(df.Message,df.spam,test_size=0.2)

In [12]:
X_train.shape

(4457,)

In [13]:
X_test.shape

(1115,)

In [14]:
X_train[:4]

302     Shit that is really shocking and scary, cant i...
118     Goodo! Yes we must speak friday - egg-potato r...
442                You were supposed to wake ME up &gt;:(
2356    Hello, my love ! How went your day ? Are you a...
Name: Message, dtype: object

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
cv=v.fit_transform(X_train.values)

In [17]:
v.vocabulary_

{'shit': 6122,
 'that': 6831,
 'is': 3738,
 'really': 5633,
 'shocking': 6130,
 'and': 973,
 'scary': 5955,
 'cant': 1646,
 'imagine': 3606,
 'for': 2933,
 'second': 5995,
 'def': 2221,
 'up': 7199,
 'night': 4785,
 'out': 5026,
 'do': 2375,
 'think': 6864,
 'there': 6850,
 'somewhere': 6334,
 'could': 2031,
 'crash': 2060,
 'save': 5940,
 'on': 4951,
 'taxi': 6744,
 'goodo': 3182,
 'yes': 7698,
 'we': 7429,
 'must': 4663,
 'speak': 6388,
 'friday': 2993,
 'egg': 2550,
 'potato': 5358,
 'ratio': 5603,
 'tortilla': 7003,
 'needed': 4737,
 'you': 7713,
 'were': 7468,
 'supposed': 6645,
 'to': 6950,
 'wake': 7373,
 'me': 4407,
 'gt': 3247,
 'hello': 3388,
 'my': 4671,
 'love': 4226,
 'how': 3509,
 'went': 7466,
 'your': 7717,
 'day': 2183,
 'are': 1059,
 'alright': 936,
 'of': 4907,
 'sweet': 6675,
 'send': 6033,
 'jolt': 3845,
 'heart': 3372,
 'remind': 5712,
 'can': 1634,
 'hear': 3368,
 'it': 3750,
 'screamed': 5978,
 'across': 806,
 'the': 6834,
 'sea': 5989,
 'all': 923,
 'world': 7605,
 'ahmad': 886,
 'al': 906,
 'hallaq': 3292,
 'loved': 4227,
 'owned': 5055,
 'possessive': 5345,
 'passionate': 5125,
 'kiss': 3947,
 'will': 7524,
 'take': 6711,
 'care': 1658,
 'financial': 2846,
 'problem': 5454,
 'help': 3391,
 'dont': 2411,
 'forget': 2939,
 'place': 5247,
 'as': 1095,
 'many': 4350,
 'free': 2977,
 'requests': 5744,
 'with': 7556,
 '1stchoice': 335,
 'co': 1868,
 'uk': 7135,
 'wish': 7548,
 'more': 4590,
 'information': 3664,
 'call': 1611,
 '08707808226': 89,
 'ill': 3598,
 'down': 2430,
 'soon': 6345,
 'photoshop': 5217,
 'makes': 4327,
 'computer': 1945,
 'shut': 6168,
 'freemsg': 2983,
 'fancy': 2769,
 'flirt': 2892,
 'reply': 5737,
 'date': 2175,
 'now': 4855,
 'join': 3836,
 'uks': 7137,
 'fastest': 2781,
 'growing': 3239,
 'mobile': 4548,
 'dating': 2178,
 'service': 6054,
 'msgs': 4631,
 'rcvd': 5611,
 'just': 3872,
 '25p': 372,
 'optout': 4991,
 'txt': 7112,
 'stop': 6522,
 '83021': 666,
 'cool': 2004,
 'want': 7391,
 'go': 3152,
 'kappa': 3892,
 'or': 4992,
 'should': 6146,
 'meet': 4425,
 'outside': 5037,
 'mu': 4641,
 'so': 6306,
 'people': 5166,
 'seems': 6013,
 'be': 1287,
 'special': 6390,
 'at': 1125,
 'first': 2864,
 'sight': 6178,
 'but': 1580,
 'only': 4963,
 'very': 7290,
 'few': 2815,
 'remain': 5705,
 'till': 6917,
 'last': 4021,
 'maintain': 4323,
 'them': 6841,
 'life': 4098,
 'ends': 2592,
 'sh': 6075,
 'jas': 3790,
 'schedule': 5959,
 'next': 4773,
 'week': 7447,
 'am': 945,
 'town': 7018,
 'this': 6871,
 'weekend': 7449,
 'li': 4089,
 'hai': 3284,
 'bored': 1442,
 'da': 2147,
 'lecturer': 4064,
 'repeating': 5732,
 'weeks': 7452,
 'stuff': 6568,
 'waste': 7407,
 'time': 6919,
 'nothing': 4845,
 'smsing': 6289,
 'xy': 7672,
 'lor': 4205,
 'sorry': 6355,
 'guys': 3271,
 'neva': 4760,
 'in': 3630,
 'person': 5184,
 'they': 6857,
 'sort': 6356,
 'know': 3959,
 'wan': 7387,
 'ask': 1103,
 'bring': 1512,
 'along': 933,
 'our': 5024,
 'meeting': 4427,
 'filthy': 2840,
 'stories': 6532,
 'girls': 3131,
 'waiting': 7372,
 'oh': 4928,
 'ho': 3447,
 'use': 7236,
 'these': 6852,
 'type': 7123,
 'words': 7598,
 'today': 6956,
 'going': 3164,
 'college': 1897,
 'not': 4840,
 'able': 766,
 'atten': 1135,
 'class': 1828,
 'when': 7485,
 'feel': 2800,
 'better': 1345,
 'than': 6822,
 'silence': 6185,
 'gud': 3251,
 'mrng': 4622,
 'hi': 3415,
 'its': 3758,
 'jess': 3815,
 'if': 3585,
 'work': 7599,
 'im': 3602,
 'home': 3461,
 'eve': 2658,
 'xxx': 7664,
 'company': 1925,
 'good': 3173,
 'environment': 2623,
 'terrific': 6797,
 'food': 2924,
 'nice': 4777,
 'hook': 3473,
 'any': 1005,
 'told': 6965,
 'her': 3401,
 'had': 3280,
 'dr': 2437,
 'appt': 1048,
 'she': 6098,
 'thinks': 6867,
 'gonna': 3171,
 'die': 2309,
 'check': 1753,
 'worried': 7608,
 'about': 767,
 'didn': 2306,
 'listen': 4139,
 'solve': 6317,
 'case': 1679,
 'man': 4336,
 'was': 7403,
 'found': 2958,
 'murdered': 4656,
 'lt': 4249,
 'decimal': 2208,
 'afternoon': 863,
 'his': 3431,
 'wife': 7515,
 'called': 1617,
 'police': 5311,
 'questioned': 5554,
 'everyone': 2670,
 'sir': 6208,
 'sleeping': 6244,
 'murder': 4655,
 'took': 6987,
 'cook': 2000,
 'cooking': 2003,
 'gardener': 3070,
 'picking': 5225,
 'vegetables': 7280,
 'house': 3504,
 'maid': 4317,
 'post': 5350,
 'office': 4917,
 'children': 1786,
 'play': 5261,
 'neighbour': 4747,
 'marriage': 4365,
 'arrested': 1084,
 'murderer': 4657,
 'immediately': 3613,
 'who': 7501,
 'reason': 5637,
 'brilliant': 1509,
 'purchase': 5525,
 'mail': 4318,
 'have': 3348,
 'po': 5287,
 'box': 1460,
 'number': 4869,
 'sent': 6042,
 'again': 867,
 'piss': 5242,
 'talking': 6720,
 'someone': 6323,
 'realise': 5627,
 'point': 5307,
 'read': 5621,
 'backwards': 1207,
 'see': 6007,
 'forwarding': 2957,
 'message': 4456,
 'proof': 5485,
 'thanks': 6826,
 'from': 3014,
 'tescos': 6800,
 'quite': 5560,
 'gone': 3169,
 'eat': 2522,
 'jap': 3788,
 'done': 2409,
 'oso': 5014,
 'aft': 860,
 'ur': 7218,
 'lect': 4062,
 'wat': 7410,
 'got': 3189,
 '12': 276,
 'rite': 5812,
 'sore': 6352,
 'throat': 6890,
 'scratches': 5975,
 'talk': 6718,
 'dear': 2195,
 'why': 7509,
 'mood': 4587,
 'off': 4909,
 'drive': 2457,
 'brother': 1528,
 'thanx': 6829,
 'lot': 4213,
 'important': 3618,
 'orange': 4994,
 'user': 7239,
 '0789xxxxxxx': 37,
 'lucky': 4255,
 '2find': 390,
 'log': 4175,
 'onto': 4966,
 'http': 3523,
 'www': 7647,
 'urawinner': 7219,
 'com': 1902,
 'fantastic': 2772,
 'surprise': 6656,
 'awaiting': 1175,
 'much': 4643,
 'payed': 5142,
 'suganya': 6607,
 'then': 6845,
 'sleep': 6242,
 'dun': 2491,
 'disturb': 2363,
 'liao': 4090,
 'msg': 4625,
 'feb': 2796,
 'dis': 2343,
 'valued': 7267,
 'frnds': 3007,
 'evn': 2679,
 'comes': 1910,
 'back': 1205,
 'll': 4156,
 'married': 4366,
 'luv': 4265,
 'ignore': 3590,
 'lose': 4207,
 'evr': 2683,
 'jason': 3791,
 'says': 5948,
 'pick': 5223,
 'some': 6319,
 'like': 4110,
 'an': 968,
 'hour': 3501,
 'ya': 7674,
 'remember': 5708,
 'haven': 3350,
 'heard': 3369,
 'anything': 1013,
 'he': 3358,
 'answering': 997,
 'texts': 6819,
 'guessing': 3259,
 'flaked': 2878,
 'said': 5897,
 'jb': 3798,
 'those': 6878,
 'ducking': 2483,
 'chinchillas': 1792,
 'guess': 3255,
 'which': 7495,
 'pub': 5513,
 'happy': 3322,
 'pig': 5234,
 'clover': 1855,
 'whatever': 7481,
 'saying': 5947,
 'wait': 7369,
 'bus': 1574,
 'innocent': 3675,
 'fun': 3033,
 'please': 5269,
 '08712402779': 105,
 'urgent': 7222,
 'coming': 1914,
 'miss': 4511,
 'desparate': 2270,
 'recorded': 5663,
 'left': 4065,
 'other': 5016,
 'sound': 6364,
 'voice': 7334,
 'hey': 3411,
 'darlin': 2167,
 'tell': 6775,
 'wen': 7464,
 'where': 7489,
 'mt': 4633,
 'pete': 5194,
 'xx': 7661,
 'tv': 7100,
 'show': 6153,
 'start': 6474,
 'leh': 4071,
 'still': 6511,
 'busy': 1579,
 'doing': 2397,
 'report': 5740,
 'late': 4023,
 'need': 4736,
 'get': 3110,
 'laptop': 4013,
 '26th': 375,
 'july': 3865,
 'loving': 4236,
 'rock': 5820,
 'cash': 1680,
 'balance': 1219,
 'currently': 2123,
 '500': 539,
 'pounds': 5364,
 'maximize': 4396,
 '86688': 696,
 '150p': 303,
 'cc': 1697,
 '08718720201': 140,
 '114': 269,
 '14': 291,
 'tcr': 6752,
 'w1': 7350,
 'eatin': 2524,
 'lunch': 4261,
 'ever': 2664,
 'green': 3224,
 'quote': 5566,
 'by': 1595,
 'jerry': 3813,
 'cartoon': 1678,
 'irritates': 3734,
 'always': 943,
 'one': 4957,
 'loves': 4234,
 'vry': 7346,
 'fails': 2749,
 'express': 2725,
 'nyt': 4886,
 'sweater': 6673,
 'fr': 2966,
 'mango': 4346,
 'no': 4804,
 'size': 6222,
 'already': 935,
 'irritating': 3735,
 'tunji': 7093,
 'queen': 5550,
 'wishing': 7552,
 'great': 3220,
 'abiola': 764,
 'later': 4026,
 'though': 6881,
 'continued': 1991,
 'support': 6642,
 'question': 5553,
 'enter': 2611,
 'in2': 3631,
 'draw': 2443,
 '100': 251,
 'name': 4692,
 'new': 4766,
 'us': 7232,
 'president': 5416,
 'ans': 992,
 '80082': 646,
 'aight': 891,
 'latest': 4027,
 'probably': 5453,
 'closer': 1850,
 'jay': 3793,
 'tyler': 7122,
 'two': 7110,
 'trips': 7058,
 'friends': 2998,
 'stay': 6487,
 'fb': 2793,
 'chat': 1743,
 'well': 7461,
 'until': 7197,
 'slightly': 6254,
 'disastrous': 2347,
 'pm': 5285,
 'fav': 2787,
 'darlings': 2169,
 'hope': 3477,
 'ok': 4933,
 'coffee': 1880,
 'wld': 7571,
 'tomorrow': 6975,
 'same': 5911,
 'friendship': 3000,
 'game': 3059,
 'word': 7597,
 'say': 5945,
 'doesn': 2385,
 'march': 4355,
 'may': 4398,
 'yesterday': 7700,
 'pls': 5277,
 'make': 4326,
 'note': 4841,
 'exposed': 2724,
 'also': 938,
 'find': 2847,
 'school': 5960,
 'anyone': 1009,
 'else': 2570,
 'vomiting': 7339,
 'dog': 2387,
 'cat': 1687,
 'let': 4084,
 'thats': 6833,
 'princess': 5438,
 'cover': 2046,
 'face': 2739,
 'hot': 3495,
 'sticky': 6508,
 'cum': 2115,
 'taking': 6715,
 'sq825': 6447,
 'reaching': 5618,
 'ard': 1058,
 'smth': 6292,
 'dat': 2173,
 'arrival': 1085,
 'clothes': 1854,
 'jewelry': 3818,
 'plz': 5284,
 'calling': 1623,
 'amp': 961,
 'asks': 1108,
 'disconnect': 2349,
 'coz': 2049,
 'iz': 3768,
 'attempt': 1134,
 'terrorist': 6799,
 'sim': 6190,
 'card': 1655,
 'itz': 3762,
 'confirmd': 1961,
 'nokia': 4814,
 'motorola': 4606,
 'has': 3333,
 'been': 1307,
 'verified': 7285,
 'cnn': 1866,
 'ibn': 3564,
 'registered': 5692,
 'subscriber': 6586,
 'yr': 7726,
 'gift': 3121,
 'voucher': 7343,
 'entered': 2612,
 'receipt': 5648,
 'correct': 2014,
 'olympics': 4948,
 '80062': 644,
 'cabin': 1600,
 'pa': 5062,
 'boss': 1447,
 'felt': 2809,
 'askd': 1104,
 'after': 861,
 'invited': 3714,
 'apartment': 1021,
 'iam': 3559,
 'addicted': 822,
 'msging': 4627,
 'wrong': 7635,
 'bcoz': 1281,
 'don': 2407,
 'bslvyl': 1539,
 'getting': 3115,
 'wonderful': 7588,
 'caring': 1667,
 'best': 1339,
 'god': 3158,
 'yours': 7721,
 'him': 3425,
 'noe': 4808,
 'tmr': 6944,
 'mom': 4568,
 'might': 4474,
 'omw': 4950,
 'castor': 1686,
 'dude': 2484,
 'afraid': 857,
 'faith': 2753,
 'things': 6863,
 'possible': 5348,
 'beautiful': 1294,
 'three': 6887,
 'christmas': 1811,
 'merry': 4453,
 'taught': 6741,
 'ranjith': 5598,
 'sms': 6287,
 'becaus': 1297,
 'hes': 3406,
 'verifying': 7287,
 'project': 5472,
 'prabu': 5377,
 'mistake': 4521,
 're': 5614,
 'buy': 1585,
 'drop': 2463,
 'tonight': 6982,
 'total': 7009,
 'order': 4998,
 'quarter': 5548,
 'enough': 2609,
 'does': 2383,
 'own': 5054,
 'most': 4598,
 'fixes': 2875,
 'spelling': 6403,
 'sometimes': 6331,
 'gets': 3113,
 'completely': 1936,
 'diff': 2314,
 'figure': 2828,
 'id': 3573,
 'bowls': 1459,
 'worth': 7614,
 'safe': 5892,
 'selfish': 6023,
 'thank': 6825,
 'unsubscribed': 7195,
 'services': 6055,
 'tons': 6984,
 'sexy': 6071,
 'babes': 1198,
 'hunks': 3540,
 'straight': 6537,
 'phone': 5209,
 'gotbabes': 3191,
 'subscriptions': 6589,
 'reach': 5615,
 'around': 1079,
 'cann': 1643,
 'asa': 1096,
 'did': 2304,
 'persons': 5189,
 'story': 6534,
 'result': 5769,
 'raji': 5583,
 'favour': 2791,
 'convey': 1997,
 'birthday': 1376,
 'wishes': 7550,
 'nimya': 4794,
 'dunno': 2493,
 'juz': 3876,
 'askin': 1106,
 'cos': 2019,
 '20': 343,
 'salon': 5905,
 'hair': 3285,
 'sense': 6039,
 'tot': 7008,
 'cut': 2134,
 'text': 6808,
 'parked': 5107,
 'specify': 6395,
 'domain': 2406,
 'nusstu': 4875,
 'sch': 5958,
 'trouble': 7062,
 '4d': 515,
 'dad': 2149,
 '1405': 293,
 '1680': 315,
 '1843': 320,
 'big': 1359,
 'small': 6267,
 'sat': 5929,
 'sun': 6623,
 'little': 4147,
 'far': 2774,
 'run': 5871,
 'tomo': 6973,
 'believe': 1322,
 'rayan': 5607,
 'macleran': 4296,
 'height': 3382,
 'recycling': 5669,
 'twice': 7104,
 'spend': 6404,
 'earning': 2512,
 'money': 4575,
 'spent': 6406,
 'spending': 6405,
 'morning': 4594,
 'keep': 3904,
 'smiling': 6280,
 '09061743810': 199,
 'landline': 4003,
 'abta': 775,
 'complimentary': 1940,
 'tenerife': 6789,
 'holiday': 3456,
 '5000': 540,
 'await': 1174,
 'collection': 1896,
 'sae': 5890,
 'cs': 2094,
 '326': 447,
 'cw25wx': 2142,
 '150': 301,
 'ppm': 5373,
 'spoons': 6430,
 'okay': 4934,
 'trying': 7076,
 'contact': 1981,
 'todays': 6957,
 'shows': 6161,
 'won': 7584,
 '800': 642,
 'prize': 5448,
 'guaranteed': 3250,
 '09050000460': 163,
 'land': 4001,
 'line': 4123,
 'claim': 1822,
 'j89': 3771,
 'box245c2150pm': 1461,
 'shirt': 6120,
 'having': 3354,
 'online': 4961,
 'haf': 3281,
 'canteen': 1648,
 'missing': 4515,
 'too': 6986,
 'pray': 5392,
 'inshah': 3681,
 'allah': 924,
 'gr8': 3199,
 'poly': 5314,
 'tones': 6978,
 'mobs': 4553,
 'direct': 2337,
 '2u': 420,
 'rply': 5851,
 'title': 6934,
 '8007': 645,
 'eg': 2548,
 'breathe1': 1499,
 'titles': 6935,
 'crazyin': 2066,
 'sleepingwith': 6245,
 'finest': 2850,
 'ymca': 7708,
 'getzed': 3116,
 'pobox365o4w45wq': 5294,
 '300p': 432,
 'wah': 7364,
 'hee': 3380,
 'form': 2946,
 'clark': 1826,
 'utter': 7249,
 'finish': 2852,
 'yar': 7679,
 'mushy': 4660,
 'embarrassed': 2578,
 'excellent': 2693,
 'ready': 5625,
 'moan': 4545,
 'scream': 5977,
 'ecstasy': 2530,
 'yeah': 7686,
 'basically': 1253,
 'away': 1179,
 'before': 1311,
 'bout': 1456,
 '30ish': 434,
 'what': 7480,
 'welcome': 7459,
 'select': 6018,
 'o2': 4889,
 'added': 821,
 'benefits': 1336,
 'specially': 6393,
 'trained': 7028,
 'advisors': 846,
 'dialling': 2295,
 '402': 481,
 'cheers': 1763,
 'year': 7687,
 'wit': 7555,
 'different': 2318,
 'stalk': 6463,
 'profiles': 5468,
 '85233': 690,
 'ringtone': 5804,
 'real': 5626,
 'battery': 1266,
 'mr': 4620,
 'adewale': 827,
 'uncle': 7150,
 'aka': 904,
 'egbon': 2549,
 'watching': 7414,
 'telugu': 6781,
 'movie': 4614,
 'abt': 774,
 'sounds': 6366,
 'come': 1908,
 'vikky': 7308,
 'otside': 5021,
 'nw': 4881,
 'il': 3597,
 'tht': 6898,
 'calls': 1625,
 'treadmill': 7046,
 'sure': 6649,
 'working': 7603,
 'ad': 817,
 'craigslist': 2057,
 'selling': 6026,
 'chance': 1721,
 'reality': 5629,
 'fantasy': 2773,
 '08707509020': 87,
 '20p': 354,
 'per': 5168,
 'min': 4484,
 'ntt': 4863,
 'ltd': 4250,
 '1327': 290,
 'croydon': 2086,
 'cr9': 2054,
 '5wb': 567,
 '0870': 66,
 'national': 4711,
 'rate': 5600,
 'asked': 1105,
 '3mobile': 469,
 'chatlines': 1745,
 'inclu': 3636,
 'mins': 4497,
 'india': 3651,
 'cust': 2127,
 'servs': 6057,
 'sed': 6006,
 'l8er': 3982,
 'mega': 4431,
 'bill': 1363,
 'giv': 3133,
 'bailiff': 1214,
 'due': 2486,
 'days': 2184,
 '250': 369,
 'reg': 5686,
 'ciao': 1815,
 'way': 7424,
 'tirupur': 6931,
 'feeling': 2802,
 'fill': 2833,
 'missed': 4513,
 'mumhas': 4650,
 'beendropping': 1308,
 'red': 5670,
 'wine': 7534,
 'over': 5043,
 'theplace': 6848,
 'adress': 835,
 'hoping': 3483,
 'langport': 4007,
 'anyway': 1016,
 'holla': 3457,
 'whenever': 7486,
 'because': 1298,
 'excuse': 2698,
 'creep': 2075,
 'sarasota': 5922,
 'valentine': 7261,
 'answers': 998,
 'ques': 5552,
 'colour': 1899,
 'suits': 6615,
 'their': 6838,
 'list': 4137,
 'fullonsms': 3032,
 'visit': 7323,
 'walmart': 7385,
 'bath': 1260,
 'fine': 2849,
 'ain': 892,
 'answerin': 996,
 'actually': 816,
 'pretty': 5425,
 'reasonable': 5638,
 'sleepy': 6248,
 'bye': 1597,
 'even': 2660,
 'team': 6759,
 'macho': 4295,
 'budget': 1551,
 'bb': 1270,
 'bold': 1423,
 'saw': 5944,
 'dollars': 2403,
 'mind': 4486,
 '1st': 333,
 'prob': 5452,
 'nan': 4698,
 'sonathaya': 6338,
 'soladha': 6316,
 'hun': 3536,
 'onbus': 4953,
 'goin': 3162,
 'wants': 7395,
 '2go': 393,
 '4a': 513,
 'meal': 4408,
 'donyt': 2415,
 'cuz': 2141,
 'latelyxxx': 4025,
 'polyphonic': 5319,
 'tone': 6977,
 'mob': 4546,
 'every': 2665,
 'pt2': 5510,
 '87575': 706,
 'txtin': 7115,
 '16': 313,
 'hl': 3439,
 '4info': 523,
 'havent': 3351,
 'wined': 7535,
 'dined': 2328,
 'request': 5743,
 'melle': 4435,
 'oru': 5011,
 'minnaminunginte': 4495,
 'nurungu': 4873,
 'vettam': 7291,
 'set': 6058,
 'callertune': 1620,
 'callers': 1619,
 'press': 5419,
 'copy': 2009,
 'sinco': 6198,
 'payee': 5144,
 'icicibank': 3571,
 'urn': 7230,
 'confirm': 1960,
 'beware': 1350,
 'frauds': 2973,
 'share': 6091,
 'disclose': 2348,
 'easy': 2521,
 'mate': 4381,
 'quick': 5556,
 'drink': 2452,
 'bit': 1378,
 'ambitious': 948,
 'plenty': 5274,
 'water': 7416,
 'cr': 2052,
 'yo': 7709,
 'stock': 6514,
 'dubsack': 2481,
 'nope': 4825,
 'since': 6197,
 'ayo': 1189,
 'travelled': 7044,
 'forgotten': 2944,
 'guy': 3270,
 'finished': 2854,
 'yet': 7701,
 'discussed': 2354,
 'mother': 4600,
 ...}

In [18]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [23]:
X_train[:4][302]

'Shit that is really shocking and scary, cant imagine for a second. Def up for night out. Do u think there is somewhere i could crash for night, save on taxi?'

In [26]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(cv,y_train)

MultinomialNB()

In [28]:
cv_test= v.transform(X_test)

In [29]:
from sklearn.metrics import classification_report

y_pred= model.predict(cv_test)

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       955
           1       0.97      0.94      0.95       160

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [36]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [37]:
y_pred = clf.predict(X_test)

In [38]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      0.99      0.99       955\n           1       0.97      0.94      0.95       160\n\n    accuracy                           0.99      1115\n   macro avg       0.98      0.97      0.97      1115\nweighted avg       0.99      0.99      0.99      1115\n'

Bag of words: Exercises
In this Exercise, you are going to classify whether a given movie review is positive or negative.
you are going to use Bag of words for pre-processing the text and apply different classification algorithms.
Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

In [1]:
#Import necessary libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

About Data: IMDB Dataset
Credits: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews?resource=download

This data consists of two columns. - review - sentiment
Reviews are the statements given by users after watching the movie.
sentiment feature tells whether the given review is positive or negative.

In [3]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
df= pd.read_csv('movies_sentiment_data.csv')



#2. print the shape of the data
print(df.shape)


#3. print top 5 datapoints
df.head(5)

(19000, 2)

                                              review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [7]:
#creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative
df['Category']=df['sentiment'].apply(lambda x: 1 if x=='positive'else 0)
df.head(5)

                                              review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [10]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.
df.Category.value_counts()

Category
1    9500
0    9500
Name: count, dtype: int64

In [11]:
#Do the 'train-test' splitting with test size of 20%

X_train,X_test,y_train,y_test= train_test_split(df.review,df.Category,test_size=0.2)

In [12]:
X_train.shape

(15200,)

In [13]:
X_train.head()

13413    Beyond The Clouds is a hauntingly beautiful, e...
15473    CAMILLE 2000 <br /><br />Aspect ratio: 2.35:1 ...
18030    This was probably the worst movie i have ever ...
12676    What is happening to ITV Drama. First, "Losing...
10857    I haven't seen this movie in about 5 years, bu...
Name: review, dtype: object

Exercise-1

using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.
Note:

use CountVectorizer for pre-processing the text.

use Random Forest as the classifier with estimators as 50 and criterion as entropy.

print the classification report.

References:

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [14]:
#1. create a pipeline object


clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('rfc', RandomForestClassifier(n_estimators=50,criterion='entropy'))
])


#2. fit with X_train and y_train

clf.fit(X_train, y_train)

#3. get the predictions for X_test and store it in y_pred

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

#4. print the classfication report

              precision    recall  f1-score   support

           0       0.83      0.84      0.84      1891
           1       0.84      0.83      0.84      1909

    accuracy                           0.84      3800
   macro avg       0.84      0.84      0.84      3800
weighted avg       0.84      0.84      0.84      3800

Exercise-2

using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..
Note:

use CountVectorizer for pre-processing the text.
use KNN as the classifier with n_neighbors of 10 and metric as 'euclidean'.
print the classification report.
References:

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [15]:
#1. create a pipeline object
knn=Pipeline([
    ('vectorizer', CountVectorizer()),
    ('knc', KNeighborsClassifier(n_neighbors=10,metric='euclidean'))
])

#2. fit with X_train and y_train
knn.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = knn.predict(X_test)

print(classification_report(y_test, y_pred))

#4. print the classfication report

              precision    recall  f1-score   support

           0       0.63      0.67      0.65      1891
           1       0.65      0.61      0.63      1909

    accuracy                           0.64      3800
   macro avg       0.64      0.64      0.64      3800
weighted avg       0.64      0.64      0.64      3800

Exercise-3

using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..
Note:

use CountVectorizer for pre-processing the text.
use Multinomial Naive Bayes as the classifier.
print the classification report.
References:

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html

In [16]:
#1. create a pipeline object

multi=Pipeline([
    ('vectorizer', CountVectorizer()),
    ('mnb', MultinomialNB())
])


#2. fit with X_train and y_train
multi.fit(X_train, y_train)



#3. get the predictions for X_test and store it in y_pred

y_pred = multi.predict(X_test)

print(classification_report(y_test, y_pred))


#4. print the classfication report

              precision    recall  f1-score   support

           0       0.82      0.89      0.86      1891
           1       0.88      0.81      0.85      1909

    accuracy                           0.85      3800
   macro avg       0.85      0.85      0.85      3800
weighted avg       0.85      0.85      0.85      3800

Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?

As we are using bag of words to convert text into vectors.It does not take alot of factors while creating vector like order of words or sarcasm in the tone. Which means the vectors neardby not necessary share the same sentiment.